// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Shared Firebase project with ScrapVal (kabadi) customer app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69cQ-RIeGSm6JFT-EShESlnMDgwpWsFc',
    appId: '1:124131366432:web:024f3059245b3d23954e45',
    messagingSenderId: '124131366432',
    projectId: 'kabad-8fbc6',
    authDomain: 'kabad-8fbc6.firebaseapp.com',
    storageBucket: 'kabad-8fbc6.firebasestorage.app',
    measurementId: 'G-BRCWTTMLFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoR09zrnAksJOv_LrQ7hcEwH5R3xCJEM0',
    appId: '1:124131366432:android:17db81b99cd52643954e45',
    messagingSenderId: '124131366432',
    projectId: 'kabad-8fbc6',
    storageBucket: 'kabad-8fbc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsjVMkbqAfr39T5F16C1BXD3faDchwgxA',
    appId: '1:124131366432:ios:f02ad2b92a21b860954e45',
    messagingSenderId: '124131366432',
    projectId: 'kabad-8fbc6',
    storageBucket: 'kabad-8fbc6.firebasestorage.app',
    iosBundleId: 'com.scrapwell.partner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsjVMkbqAfr39T5F16C1BXD3faDchwgxA',
    appId: '1:124131366432:ios:f02ad2b92a21b860954e45',
    messagingSenderId: '124131366432',
    projectId: 'kabad-8fbc6',
    storageBucket: 'kabad-8fbc6.firebasestorage.app',
    iosBundleId: 'com.scrapwell.partner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69cQ-RIeGSm6JFT-EShESlnMDgwpWsFc',
    appId: '1:124131366432:web:8a9dd96de1f3319d954e45',
    messagingSenderId: '124131366432',
    projectId: 'kabad-8fbc6',
    authDomain: 'kabad-8fbc6.firebaseapp.com',
    storageBucket: 'kabad-8fbc6.firebasestorage.app',
    measurementId: 'G-MEQW3RZC8M',
  );
}
